LibreHealthIO/lh-ehr

library/patient_tracker.inc.php

Patient Flow Board Fix for typo that got into the old code

Patient Flow Board Fix

---

interface/patient_file/deleter.php
interface/patient_file/summary/demographics.php
library/globals.inc.php

Control the patient delete button with a global entry, defaults to off

Control the patient delete button with a global entry, defaults to off

---

interface/billing/sl_receipts_report.php
library/globals.inc.php

Added option to Cash Receipts Report to show Patient Name instead of
invoice number.
Also converted the Cash Receipts Report to standard security model.

Added option and converted to standard security model

---

interface/reports/patient_flow_board_report.php

removed unneeded code and comment

removed unneeded code and comment

---

interface/main/tabs/menu/menu_updates.php

removed debug statement

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
interface/themes/ajax_calendar.css

Make provider multiselect mo-bigga.  add horizontal scroll to calendar
in case you have more than two providers.

tweak_usability_issues

---

library/globals.inc.php

TESTED AND WORKING
@teryhill  please confirm.

Fix globals.inc

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/orig_default.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
interface/usergroup/user_admin.php

This allows viewing of All facilities *assigned to a provider* with the facility ACL turned on.  Still need calendar view to select "All Facilities" by default.  Without this change, a provider with multiple facilities cannot see their whole schedule.
commit notes:
Still has issue with default facility stuff.  Still need default to all assigned.
Little more direct this time.  Replacement branch.  Easier to do as I am now not trying to do it with conflicts caused by having to have the application running to test the fix I needed to test due to the other fix not being fixed...  :)

FAC_ACL_FIX_Clean

---

library/sql_upgrade_fx.php

Please check this fix for unexpected behavior.  see #37

Fix syntax error, php7 exposed it

---

library/gen_x12_837.inc.php

snuffing 4010 code from gen837

remove 4010 standard

---

library/pnotes.inc

pnotes_query_bug_fix

---

library/globals.inc.php

the fix is in

---

setup.php

change contact information #54

---

interface/themes/rtl.css
interface/themes/style_babyblu.css
interface/themes/style_blue.css
interface/themes/style_light.css
interface/themes/style_metal.css
interface/themes/style_oemr.css
interface/themes/style_pdf.css
interface/themes/style_purple.css
interface/themes/style_sky_blue.css
interface/themes/style_tan_no_icons.css

delete unused style elements

---

acknowledge_license_cert.html

Changes to the acknowledgments page.

Changes to the acknowledgments page

---

interface/patient_file/history/encounters.php

here is the fix for unknown

---

library/gen_x12_837.inc.php

This fixes a bad commit in 4010 removal.  This also verifies testing of
the freeb removal.

Some leftover braces.

---

sql/0_0_1-to-1_0_0_upgrade.sql

I have not had the existing code fail, but...I ain't using the cutting
edge of the butter knife.  Try these wrapper tags.

#108 possible fix

---

sql/0_0_1-to-1_0_0_upgrade.sql

fix that worked for me #108 Script failing

fix that worked for me

---

interface/billing/sl_eob_search.php
library/globals.inc.php
sites/default/statement.inc.php

Statement changes

---

interface/patient_tracker/patient_tracker.php

moves provider to the top of screen if single provider From MdSupport #133

moves provider to the top of screen if single provider

---

library/globals.inc.php

Added https://forums.librehealth.io/c/7-support ref issue #81

Support forum Link

---

interface/globals.php
interface/main/tabs/templates/user_data_template.php

Used to turn options on and off for development Used to turn off left
nav untill we decide to eliminate it. #142

# 142 Added a development Flag

---

interface/forms/annotate_diagram/selectnew.php

Fixed the word click and added the header. This header needs to be reviewed #148

Fixed the word click and added the header

---

interface/main/dated_reminders/dated_reminders.php
interface/main/dated_reminders/dated_reminders_add.php
interface/main/dated_reminders/dated_reminders_log.php

Alphabetize the user dropdown list, ensure that the list contains only
real local users by checking some additional fields, make the select
show 8 instead of the default 5, and set the list of reminders to 15
instead of just 5.  One heavy user has theirs set to 50, so this is a
minimal compromise.

dated reminders #144  user selection box ORDER, WHERE, and size change

---

interface/main/left_nav.php
interface/main/tabs/menu/menu_data.php
library/globals.inc.php

Rename Patients menu item to Finder, add option to globals

---

acknowledge_license_cert.html

changes to add health disclaimer in conjunction with #79

changes to add health disclaimer

---

interface/main/tabs/js/tabs_view_model.js
sites/default/menu_data.json

Needed unique names for menu items, as well as set the closable
attribute to true.

cure unclosable and stomp menu

---

interface/billing/sl_eob_search.php

variable assignment by reference is implied

PHP7 upgrade for Posting Screen #186 

---

library/globals.inc.php

removed layout style from globals no longer needed #190

Removed Layout Style #190

---

interface/main/main_screen.php
interface/main/main_title.php

removal of gbl_nav_area_width from main title #190

removal of gbl_nav_area_width #190

---

interface/patient_file/summary/demographics.php

Removed the hook to external data #193

Removed the hook to external data #193

---

sql/libreehr_upgrade.sql
version.php

This will be the release if I get enough thumbs up...

Rel candidate 1

---

interface/main/main_screen.php
interface/main/main_title.php
library/globals.inc.php

Undo the Navigation Area width #203

Undo the removal of Navigation Area Width

---

library/globals.inc.php

Reversing the change to remove concurrent layout options #209

Reversing the change to remove concurrent layout options

---

interface/main/tabs/css/menu.css
interface/main/tabs/css/tabs.css
interface/main/tabs/js/application_view_model.js
interface/main/tabs/js/custom_bindings.js
interface/main/tabs/js/dialog_utils.js
interface/main/tabs/js/frame_proxies.js
interface/main/tabs/js/include_opener.js
interface/main/tabs/js/menu_analysis.js
interface/main/tabs/js/patient_data_view_model.js
interface/main/tabs/js/tabs_view_model.js
interface/main/tabs/js/user_data_view_model.js
interface/main/tabs/main.php
interface/main/tabs/menu/menu_data.php
interface/main/tabs/menu/menu_db.php
interface/main/tabs/menu/menu_json.php
interface/main/tabs/menu/menu_updates.php
interface/main/tabs/redirect.php
interface/main/tabs/templates/menu_template.php
interface/main/tabs/templates/patient_data_template.php
interface/main/tabs/templates/tabs_template.php

These are the files with out copyrights in the headers

Copyright kevins code

---

interface/code_systems/dataloads_ajax.php
library/standard_tables_capture.inc

remove ICD9 from external data upload #110

remove ICD9 from external data upload

---

controllers/C_InsuranceCompany.class.php

fix for ws error in insurance add #221

fix for ws error in insurance add

---

CategoryTreeMenu.js

#220  Current code requires this in the document root.  Fixes missing patient
document tree menu.

restoring CategoryTreeMenu.js to the code base.

---

templates/document_categories/general_list.html

View the document category edit template.

Document category edit error

---

gacl/soap/nusoap.php
interface/billing/billing_process.php
interface/drugs/dispense_drug.php
interface/forms/vitals/growthchart/chart.php
interface/main/calendar/modules/PostCalendar/pnblocks/calendar.php
interface/main/calendar/modules/PostCalendar/pninit.php
interface/main/calendar/modules/PostCalendar/popup.php
interface/main/calendar/modules/PostCalendar/print.php
interface/patient_file/letter.php
interface/patient_file/summary/shot_record.php
library/ajax/log_print_action_ajax.php

php7 return value by new fixes

---

sql/0_0_1-to-1_0_0_upgrade.sql

IfColumn requires table and column argument. #218

upgrade 001-100 fixes #218 

---

interface/billing/search_payments.php
interface/billing/sl_eob_invoice.php
library/globals.inc.php

This will allow control over deletion of payments. #10 This allows a point of control for the payment deletion. This wold be an automatic function of a month end routine if one existed (will soon hopefully)

This will allow control over deletion of payments

---

interface/usergroup/usergroup_admin.php

#235 Set a default 180 day expiration even if Global not configured to
satisfy NO ZERO DATE INNODB and strict.

Zero Date passphrase expire bug

---

interface/main/main_screen.php
interface/main/main_title.php
library/globals.inc.php

Navigation menu fix

---

custom/qrda_functions.php
interface/practice/ins_search.php

I stomped on my own code at some point.  Came up with two field name versions.  OpenEMR adopted one of them, we now have the other.

insurance_type_code field change

---

library/report_database.inc

syntax error in report_database.inc

---

interface/forms/misc_billing_options/new.php
interface/forms/misc_billing_options/report.php
interface/forms/misc_billing_options/save.php
interface/forms/misc_billing_options/table.sql
interface/forms/misc_billing_options/view.php
library/Claim.class.php
library/gen_hcfa_1500.inc.php
library/gen_hcfa_1500_02_12.inc.php
library/gen_x12_837.inc.php
sql/0_0_1-to-1_0_0_upgrade.sql
sql/database.sql

These changes allow the EPSDT options, The box 17 options, The
electronic resubmission of claims. #269

Misc_Billing_Form Changes.

---

interface/reports/edi_270.php
library/edi.inc

Changes to bring the edi 270 creation up to 5010 standard. #280

Changes to bring the edi 270 creation up to 5010 standard

---

custom/code_types.inc.php
interface/billing/billing_report.php
interface/forms/fee_sheet/new.php
interface/patient_file/encounter/superbill_custom_full.php
library/Claim.class.php
library/billing.inc
library/gen_hcfa_1500.inc.php
library/gen_x12_837.inc.php
library/globals.inc.php
sql/0_0_1-to-1_0_0_upgrade.sql
sql/database.sql

Exclude individual items from claims. #266

Exclude individual items from claims

---

library/globals.inc.php

Added CMS Margins to User Preferences and cleaned up globals. Nothing
here that OpenEMR should want. #283 (Chevy Engine)

Added CMS Margins to User Preferences and cleaned up globals

---

library/patient.inc

Fix for long standing error in billing widget. This has been around a while in OpenEMR. #285

Billing widget fix

---

interface/reports/edi_270.php
library/edi.inc

Changes per clearing house review. added a segment qualifier and changes
the DPT code #280

Changes per clearing house review

---

interface/globals.php
library/globals.inc.php

This will default the concurrent_layout setting while that code is being removed. We should be able to remove it as we come to it in a controlled manner. #288 
$GLOBALS['concurrent_layout'] = 3;

This will default the setting for concurrent_layout

---

library/globals.inc.php

Added statement tab to globals #125

Added statement tab to globals

---

interface/patient_tracker/patient_tracker.php
interface/patient_tracker/patient_tracker_status.php
interface/themes/style_babyblu.css
interface/themes/style_blue.css
interface/themes/style_light.css
interface/themes/style_metal.css
interface/themes/style_oemr.css
interface/themes/style_purple.css
interface/themes/style_sky_blue.css
interface/themes/style_tan_no_icons.css
library/ajax/drug_screen_completed.php
library/globals.inc.php
library/patient_tracker.inc.php

Changes by Matrix to allow status, provider and facility selection #311

Added Matrix's changes to Patient Flow Board

---

interface/reports/edi_276.php
library/edi_276.inc.php
library/edi_libre.inc
sites/default/menu_data.json

Claim Status Request #304 . This is currently being tested by a clearing house.

Claim Status Request

---

interface/patient_tracker/patient_tracker.php
interface/super/edit_globals.php
library/globals.inc.php

Added Global defaults  per customer request #319

Added Global defaults to PFB for status and end date

---

interface/patient_tracker/patient_tracker.php
interface/super/edit_globals.php

Fixed a typo in the date code for PFB

Fixed a typo in the date code for PFB

---

interface/patient_file/summary/demographics.php
interface/patient_file/summary/demographics_save.php
library/patient.inc

fix to insurance inactivate when creating a new patient.

fix to insurance inactivate and change web address

---

interface/forms/fee_sheet/new.php
sql/database.sql

Field in table 25 char only using 10 in program. User needed to send note on drug due to new 2017 hcpcs requirement. This field could stand to be expanded in the table to a larger value

Changed to reflect table

---

interface/main/main_title.php
interface/patient_tracker/patient_tracker.php
interface/patient_tracker/patient_tracker_status.php
interface/themes/style_babyblu.css
interface/themes/style_blue.css
interface/themes/style_light.css
interface/themes/style_metal.css
interface/themes/style_oemr.css
interface/themes/style_purple.css
interface/themes/style_sky_blue.css
interface/themes/style_tan_no_icons.css
library/globals.inc.php

Added options to hide more stuff and fixed header formatting to allow for more narrow tab presentation and use.
***BUT*** I think I broke something, looks pretty but it's not displaying any appts now :-)
@kchapple looking for someone to test.

Flowboard: new options and header formatting for small width tab

---

sql/database.sql

Fixed some structures and the list insert in to Libre calendar
categories. The categories were only loading 6,7 and 14 the rest died
silently. Cleaned up some formatting, actually my editor did.

Fixed some structures and the list insert in to Libre calendar categories

---

interface/main/about_page.php

Changed the wiki website. Changed the main website in link. Added MPL

Small fix to the about page

---

Documentation/LibreEHR.MD

Directory structure First attempt at MarkDown document

Directory structure

---

library/globals.inc.php

Tab name changes and options moved #347 #125 
I added a tab called lab, it is blank and we can remove it if it is not wanted

Tab name changes and options moved

---

library/globals.inc.php

Made change to move default code search to encounters tab #365

Made change to move default code search to encounters tab

---

interface/globals.php

changes for a new install with default panes not set #362  #361

changes for a new install with default panes not set

---

interface/patient_file/summary/demographics.php
interface/patient_file/summary/demographics_full.php
interface/patient_file/summary/demographics_save.php

This is just some cleanup and adding some IDs to sections that should have ID's so we can do styling or other DOM control sugar.

Demographics - add CSS ID to sections for later control and some cleanup

---

library/globals.inc.php

Added back hide billing widget #368

Added back hide billing widget

---

library/billing.inc
library/sql.inc

This fix is needed because of the change in table type and the removal
of the auto increment in the claims table.
Original changes from OpenEMR. Matrix and Brady (I think) #379

This is to fix an error in the reopen of the claims

---

library/Claim.class.php
library/gen_x12_837.inc.php

Added code to fully support the Box 17 enhancements to the paper form in
the electronic submission. #335

added ordering Physician from Misc Billing Form

---

sql/database.sql

Make AD auto load #356
I think this will work it needs testing

Make AD auto load

---

interface/forms/annotate_diagram/selectnew.php
sql/database.sql

fix to get AD to run

---

interface/usergroup/addrbook_edit.php
interface/usergroup/addrbook_list.php
interface/usergroup/facilities.php
interface/usergroup/facilities_add.php
interface/usergroup/user_admin.php
interface/usergroup/usergroup_admin_add.php

Added headers and changes some of the translation general cleanup

Added headers and changes some of the translation

---

interface/patient_tracker/patient_tracker.php

Harley noticed that the flow board was not properly following the global variable "Providers See Entire Calendar". We discussed and made the changes to follow the setting.  #423

Changes to work correctly with global

---

interface/reports/insurance_allocation_report.php

Added payments and adjustments to the report #426

Added payments and adjustments to the report

---

library/appointments.inc.php
library/globals.inc.php

The sort selection needed to be separate #429

This is to separate list and categories sort .

---

interface/forms/misc_billing_options/new.php
interface/forms/misc_billing_options/report.php
interface/forms/misc_billing_options/save.php
interface/forms/misc_billing_options/view.php
interface/globals.php
interface/usergroup/addrbook_edit.php
interface/usergroup/addrbook_list.php
interface/usergroup/user_admin.php
interface/usergroup/usergroup_admin.php
interface/usergroup/usergroup_admin_add.php
library/options.inc.php

Added the link to the assets. Dropdown select for state. #419

Added the link to the assets. Dropdown select for state.

---

interface/new/new.php
interface/new/new_comprehensive.php
interface/patient_file/summary/demographics_full.php
library/js/fancybox/jquery.fancybox-1.2.6.js

Working on Date picker #435 
I am missing something can you two @tmccormi  @aethelwulffe  look at this and see if you can see what I am missing.

Working on Date picker

---

interface/patient_tracker/patient_tracker.php
interface/reports/edi_270.php
interface/reports/edi_276.php
sites/default/menu_data.json

last that I see until further testing. #435

Datepicker cleanup

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html

Fix for calendar to follow time format in globals #455 
I need to look at add_edit_event and see what changes might be needed there

Fix for calendar to follow time format in globals

---

interface/main/calendar/add_edit_event.php
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html

this fixes add_edit_event to follow time global #455

this fixes add_edit_event to follow time global

---

interface/login/login.php
interface/main/tabs/css/menu.css

Fixed the height and width of input box in interface/login/login.php

---

library/options.inc.php

Fix for deceased date and financial review date #466

Fix for deceased date and financial review date

---

interface/new/new_comprehensive.php

Fix for screen not saving #460 I had the wrong version of jquery being loaded, I had 1.9.1 and it should be 1.7.2

Fix for screen not saving

---

interface/main/tabs/css/tabs.css
interface/main/tabs/main.php
interface/main/tabs/templates/tabs_template.php

Hey guys! Check out this trial version. I was initially having problems due to mouse movements being blocked by iframes but I solved it using a transparent layer whenever we are resizing
It goes a little bit crazy when 3 frames are open so I'll have to modify the formula a bit for that.
I didn't use JQueryUI because importing that whole thing for such small use seems like a waste of resources.
Thanks!

Add frame resizing capability

---

interface/forms/fee_sheet/new.php
library/Claim.class.php
library/gen_hcfa_1500.inc.php
library/gen_hcfa_1500_02_12.inc.php
library/gen_x12_837.inc.php
library/globals.inc.php

Adding Ordering, referring and contract physician to fee sheet #428.
In the HCFA 1500 Print this only changes the referring provider. If a box 17 provider is supplied on the misc billing form it is used. If there is no misc billing box 17 information, the fee sheet is checked for referring then the patient data field.
They are separate fields in the electronic form so you can have an ordering and a referring.

Adding Ordering, referring and contract physician to fee sheet

---

library/options.inc.php

Fix for nation notes change missing curly brace in options.inc good catch @pri2si17-1997

Fix for nation notes change missing curly brace in options.inc

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html

print calendar closes abruptly in chrome but works in FireFox @pri2si17-1997 thanks for finding this

print calendar closes abruptly in chrome

---

interface/main/calendar/add_edit_event.php
interface/patient_file/summary/demographics.php

fix the datepicker issues in add_edit and past appointments in demographics #480

fix the datepicker issues in add_edit and past appointments in demographics

---

interface/patient_file/summary/demographics.php

This is a patch for rel-101 branch #480

Patch for oldEvt called to include the date

---

interface/patient_file/deleter.php

bringing deleter to security standards

bringing deleter to security standards

---

interface/patient_tracker/patient_tracker.php

fix to pfb for date picker

---

interface/main/calendar/find_patient_popup.php
interface/new/new_search_popup.php
interface/patient_file/summary/demographics.php

changes to fix dates following globals

changes to fix dates following globals

---

interface/themes/ajax_calendar.css
interface/themes/style_light.css
library/js/datatables/media/css/demo_table.css

Fixed css property.

---

interface/main/tabs/main.php

Fixes #490 to most extent
Sorry for being so inactive lately. I have midterms coming next week and I have to study hard for those >_<

Fix erratic behaviour of resizing tabs

---

interface/reports/patient_list.php

Fixed Uncaught ReferenceError.

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
library/globals.inc.php

do not display canceled appointments in the calendar Per @tmccormi request

do not display canceled appointments in the calendar

---

interface/patient_file/reminder/patient_reminders.php

Fixed Uncaught reference error in patient reminder.

---

interface/new/new_comprehensive.php

DOB of insurance provider was accepting future dates. This has been fixed now.

Fixed DOB of insurance subscriber not to accept future dates

---

custom/import_xml.php

Fixed invalid import data.

---

interface/main/tabs/css/tabs.css
interface/main/tabs/templates/tabs_template.php

Partially addresses #420 
Grouped tabs is a bit complex to program, so until I can figure that out, this seems okayish.
Thanks!

Tabs follow iframes, floating unlocked tabs

---

interface/usergroup/addrbook_edit.php
interface/usergroup/addrbook_list.php

Fixed JQuery exceptions.

---

interface/patient_file/summary/add_edit_issue.php

Fixes https://github.com/LibreHealthIO/LibreEHR/issues/494
Please tell , if any more modifications are required!

added datepicker for end and start date for medications of patient

---

interface/main/calendar/find_patient_popup.php

Fixed create new patient patient from merge patient.

---

interface/billing/sl_eob_search.php

fix for statements double printing #523

fix for statements double printing

---

library/globals.inc.php
sites/default/statement.inc.php

Resolves #440 
Lines 1127-1133 of `globals.inc.php` & 107,451 of `statement.inc.php`
Couldn't really test since I was having difficulty adding payments, but I think it should work :pray: 
Thanks!

Add option to disallow printing for deceased

---

sql/database.sql

Missing portal tables

---

interface/usergroup/addrbook_edit.php
library/js/input_validate.js

This PR is a replacement of #497 for better type validation and usability.
Summary of changes::
1. Currently added an external javascript file to check type validation for Email ,Urls and Phone Numbers(US).
2. For test purpose , modified `interface/usergroup/addrbook_edit.php` . 
3. URL's can have following types: http://www.google.com.. or www.google.com or google.com.
Other Type validations would be added soon.

added external javascript file to check type validation

---

interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html

Fixed calendar print for week view and month view in chrome.

---

interface/patient_tracker/patient_tracker.php
library/globals.inc.php

This is a patch/enhancement for a customer against rel-101, I need to port it to master but it's testing well in this version.

Refined Double Booking logic, ignore canceled appts and ALL Dr views

---

README.md

added detailed installation instruction's link

---

interface/patient_file/summary/immunizations.php

There was no ` "Back to patient" ` button on `Immunizations ` tab for patient. This PR adds a back button for going back.
Also, I tried to align some code for better readability. I suggest if anyone is working on any issue, he should try to re-align the code of that particular file .

Added "Back to patient" button on immunizations 

---

assets/css/style.css
interface/forms/annotate_diagram/mapdiagram/template/css/mapdiagram.css
interface/forms/annotate_diagram/report.php
interface/forms/annotate_diagram/selectnew.php
interface/main/tabs/edit_menu.php
interface/reports/collections_report.php
patients/add_edit_event_user.php
patients/patient/styles/style.css
patients/sign/assets/signpad.css

Minor Code cleanup.
This Pull request intends to clean-up some wrong CSS comment format and extra `<tr>` in tables.

some code-cleanup

---

interface/patient_file/encounter/new_form.php

This Pull request fixes #535 . `Encounter Summary ` Tab is now getting accessed from` Administrative ` and `Clinical` Tab .

Fixes #535, Encounter Summary Tab Accesibility Bug

---

interface/billing/sl_eob_invoice.php
library/globals.inc.php
sql/database.sql

This allows the auto write off function to be turned off. It also adds
some information ti the posting screen that will be used in tracking
denials. #468

Billing changes

---

interface/patient_file/deleter.php

Fix for delete patient.

---

interface/billing/sl_eob_invoice.php

Added code to respect the delete dates. The first pass just set the
option on or off. This revision allows the user to specify a time frame. #468

Added code to respect the delete dates

---

interface/reports/pat_ledger.php

This Pull request addresses #445 . 
Note: This PR may be currently labelled as `"WORK IN PROGRESS"` , as the receipt  added currently behaves very similar to the ledger itself , having a date range to print the payments. 
@aethelwulffe @teryhill Please have look at the format and recommend some changes if required. We need to figure out a way to print a statement from the ledger itself.

Addresses #445, Adds a On-Demand Receipt

---

interface/billing/billing_report.php
library/billrep.inc

Fix for the encounter billing messages on the billing screen #557

Fix for the encounter billing messages on the billing screen

---

interface/billing/billing_report.php

I changed it to check if there are , a subscriber relationship, last name (which was there), DOB , Sex, Address, City , state for the subscriber. and if one of these are missing the name still appears in RED but now the patient name BLINKS. #562

Added some more subscriber field checking and made the name blink.

---

interface/forms/fee_sheet/new.php
interface/patient_file/encounter/new_form.php

Fixed a leftnav error and removed a left over concurrent check. Just general cleanup

Just general cleanup Fixed a leftnav error and removed a left over concurrent check

---

interface/patient_file/encounter/forms.php

added next and previous to the encounter #572

added next and previous to the encounter

---

interface/forms/misc_billing_options/new.php

Check for existing hcfa form options before allowing new one

Hcfa form check

---

interface/billing/billing_report.php

Added Provider and Referring to the search screen in billing #579

Added Provider and Referring to the search screen in billing

---

interface/globals.php
interface/new/new_comprehensive.php
interface/patient_file/summary/demographics_full.php
interface/super/edit_layout.php
library/options.inc.php

Added validations for demographics screen. Addresses #447. Integer fields aren't accepting strings anymore. New datatypes have been added namely - URL, Email, Numeric.
You all may test the work by changing datatypes from Administration/Layouts.

Added validations for demographics . Also addresses #447

---

interface/patient_file/summary/immunizations.php

Removed calendar reference that was causing the program save error

Removed calendar reference that was causing the error

---

sql/1_0_1-to-1_0_2_upgrade.sql
sql/patch.sql
sql_patch.php
sql_upgrade.php

Added back the old upgrade scripts until the new ones can be done by some one familiar with frame work #91

Added back the old upgrade scripts

---

interface/billing/billing_report.php

Added an ORDER BY name to the reffering provider and provider search.

Added an ORDER BY name to the provider search

---

library/headers.inc.php

Added CSS and common used files. @aethelwulffe

Added CSS and common used files.

---

interface/main/finder/dynamic_finder.php
interface/super/edit_globals.php
library/headers.inc.php

Decided to go with Bootstrap 3.3.4 as its already there in repo and there are a very few minor changes in 3.3.7.  Added the link to Bootstrap assets in `header.inc.php`.

UI changes in Patient Finder and Global Settings

---

interface/forms/annotate_diagram/mapdiagram/C_AbstractAnnotate.php
interface/forms/prior_auth/C_FormPriorAuth.class.php
interface/forms/ros/C_FormROS.class.php
interface/forms/vitals/C_FormVitals.class.php

clean up concurrent adds that were done by mistake

clean up concurrent adds that were done by mistake

---

interface/super/edit_globals.php

added the search that MDSupport with OpenEMR did. also did a little cleanup to some
small things. The search searches the titles and descriotion. Makes it
easier to find tags you are looking for.

added the search that MDSupport did.

---

interface/eRx_xml.php

NewCrop hates more than 3 insurances and the SQL was sending ALL of them, even if they had been replaced

Add Limit to Ins Data sql for sync to New Crop

---

controllers/C_Prescription.class.php
interface/main/finder/dynamic_finder.php
interface/patient_file/history/history_full.php
interface/super/edit_globals.php
library/headers.inc.php
templates/prescription/general_block.php
templates/prescription/general_edit.php
templates/prescription/general_fragment.php
templates/prescription/general_list.php
templates/prescription/general_lookup.php
templates/prescription/general_send.php

Removed Smarty Engine from prescription and also fixed typo in `headers.inc.php` . Had to include jquery there as Bootstrap JS required that.

Remove Smarty from Prescription Controllers&Templates

---

interface/themes/style_tan.css
interface/themes/tabs_style_compact.css
interface/themes/tabs_style_full.css
library/globals.inc.php

Dr Ray's tan css and compact and full css.

Dr Ray's tan css and compact and full css.

---

ccr/createCCRProblem.php
library/sql-ccr.inc

CCR/CCD was hard coded to just use ICD9 entries with listing problems.  Updated to ICD10 instead.

Change CCR/CCD to use ICD10 instead of ICD9

---

controllers/C_Document.class.php
controllers/C_PracticeSettings.class.php
templates/documents/general_queue.php
templates/documents/general_upload.php
templates/documents/general_view.php
templates/hl7/general_parse.php
templates/insurance_companies/general_edit.php
templates/insurance_companies/general_list.php
templates/insurance_numbers/general_edit.php
templates/insurance_numbers/general_list.php
templates/pharmacies/general_edit.php
templates/pharmacies/general_list.php
templates/practice_settings/general_list.php
templates/x12_partners/general_edit.php
templates/x12_partners/general_list.php

Bootstrap included in `Administration/Practice`.

UI-Upgrade in Administration/Practice

---

interface/patient_file/encounter/superbill_custom_full.php

Noticed that the title was not showing in the tab

Noticed that the title was not showing in the tab for codes

---

interface/patient_file/addr_label.php

fixed header and removed pubpid as requested in the review

fixed header and removed pubpid In address label change

---

library/Claim.class.php

Needed for the UB04 claim submission. Missed this file in the initial commit.

Needed for the UB04 claim submission

---

interface/patient_file/summary/stats.php

RHoyt requested the dates on medications and medical problems

RHoyt requested the dates on medications and medical problems

---

interface/patient_file/summary/immunizations.php

Fix for 500 error in Immunizations 

---

library/globals.inc.php

Since left_nav went away drop bottom pane is no longer used.

Removed references to drop bottom pane

---

interface/code_systems/dataloads_ajax.php

Title missing in tab noticed on demo site when updating ICD10's

Title missing in tab

---

interface/patient_file/summary/stats.php

Added some code to check for bad dates in the issues information. If the date is invalid it will not display.

Added some code to check for bad dates in the issues information.

---

interface/patient_tracker/patient_tracker.php

@teryhill There are a few more select inputs left to be added for flowboard preferences.
For now , you can check if it works as you desire it to work.
Also, I am working on layout things pointed out by @tmccormi . Will send that soon.

Add feature to set flowboard preferences from flowboard itself

---

interface/forms/fee_sheet/new.php
interface/forms/patient_encounter/common.php
interface/forms/vitals/templates/vitals/general_new.php
interface/main/finder/dynamic_finder.php
interface/main/messages/messages.php
interface/new/new_comprehensive.php
interface/patient_file/encounter/forms.php
interface/patient_file/history/encounters.php
interface/patient_file/history/history_full.php
interface/super/edit_globals.php
library/headers.inc.php
sites/default/sqlconf.php
templates/practice_settings/general_list.php

Adjusted call_required_libraries() function's parameters and arguments to be explicit.

Fix for #668, call_required_libraries() is badly implemented (not self-documenting).

---

interface/forms/fee_sheet/new.php
interface/forms/patient_encounter/common.php
interface/forms/vitals/templates/vitals/general_new.php
interface/main/finder/dynamic_finder.php
interface/main/messages/messages.php
interface/new/new_comprehensive.php
interface/patient_file/encounter/forms.php
interface/patient_file/history/encounters.php
interface/patient_file/history/history_full.php
interface/super/edit_globals.php
library/headers.inc.php
templates/practice_settings/general_list.php

Reverts LibreHealthIO/LibreEHR#674

Revert "Fix for #668, call_required_libraries() is badly implemented (not self-documenting)."

---

interface/patient_file/summary/demographics_full.php

Added patient name instead of current patient. #680

Added patient name instead of current patient.

---

interface/patient_tracker/patient_tracker.php

This was moved to the setting section and was not removed.

Cleanup of tracker

---

interface/usergroup/facilities_add.php

Added legal name to facility add and ordered the screen to match edit. #679

Added legal name to facility add and ordered the screen to match edit.

---

acknowledge_license_cert.html

2.0 attribution changes.
suggest that others add theirs...

Attribution update

---

acknowledge_license_cert.html

Updates part deux

---

interface/main/main_screen.php
interface/main/main_title.php
library/globals.inc.php
sites/default/menu_data.json

Some menu and globals cleanup. Took out some left nav specific stuff (tall nav, hide menu etc). Added more checks for existing globals.

Some menu and globals cleanup

---

sites/default/menu_data.json

First pass at the menu for new crop

First pass at the menu for new crop

---

library/classes/Installer.class.php

When execute SQL fails echo the message.

Display SQL Errors in Installer

---

interface/forms/ankleinjury/table.sql
interface/forms/annotate_diagram/table.sql
interface/forms/bronchitis/table.sql
interface/forms/note/table.sql
interface/forms/painmap/table.sql
interface/forms/physical_exam/table.sql
interface/forms/prior_auth/table.sql
interface/forms/reviewofs/table.sql
interface/forms/track_anything/table.sql
interface/forms/ub04_billing_options/table.sql
interface/forms/vitals/table.sql
interface/forms/vitalsM/table.sql

Remove MYISAM engine declarations

MyISAM engine declarations

---

sql/database.sql

field added and insert not updated #708

field added and insert not updated

---

sites/default/menu_data.json

fix the json file missing commas

fix the json file missing commas

---

modules/MIPS/clinical_measures.php
modules/MIPS/report_results.php

date picker css fix

---

sql/database.sql

Small fix to the patient finder criteria.

Small fix to the patient finder criteria.

---

library/classes/Installer.class.php
library/sql.inc

Fix for strict mode Have not tested yet

Fix for strict mode

---

interface/main/finder/dynamic_finder.php

If you deselect the active flag in lists the finder respects that

If you deselect the active flag in lists the finder respects that

---

sites/default/menu_data.json

Fixed for now Had a restrict on it.

NewCrop menu errors

---

Documentation/1_Installing/InstallingLibreEHR.html

Simple cleanup.  All better now.

Update xampp install docs

---

interface/main/tabs/main.php

`<title><?php echo $GLOBALS['libreehr_name'];?></title> `allows user to
identify what system they are in....vs guessing if they have more than
one system.

Configure app title

---

interface/super/edit_layout.php

Aligned buttons and gave them clearer values.

Fixing layout editor style format error

---

interface/forms/fee_sheet/new.php

Fixing Fee Sheet

---

modules/MIPS/clinical_measures.php
modules/MIPS/import_data.php
modules/filemanager/index.php

Added a closing html tag  to one file, added linked MIPS documentation.  TODO list will add a global config URL base to link documentation to CMS website or localhost.  Currently hard-coded to the SunCoast Connection website, which is the only clean set of documentation files we know of.

Minor MIPS patch

---

library/globals.inc.php
modules/calendar/index.php

Made the changes as a result of the check for new appointments being
fired to often

Changed the interval and added a no refresh on the calendar

---

modules/calendar/index.php

auto logout fix

---

acknowledge_license_cert.html

Bowen Medical URL was missing the URI.

Fix Bowen medical URL in acknowledgement file

---

interface/usergroup/addrbook_edit.php
library/globals.inc.php
modules/calendar/includes/get_provider_events.php
modules/calendar/includes/get_providers.php
modules/calendar/index.php

Calendar changes

---

interface/forms/patient_encounter/common.php

Hope this fixes the layout issue.

Addresses #741, fixes layout on encounter screen

---

sql/1_0_1-to-2_0_0_upgrade.sql

Fix clinical rules error

---

sql/1_0_1-to-2_0_0_upgrade.sql

removed the )

---

sql/1_0_1-to-2_0_0_upgrade.sql

Added remaining clinical rules fields

Added remaining clinical rules fields

---

interface/patient_tracker/patient_tracker.php

Added check for the open in new window.

Added check for the open in new window.

---

interface/usergroup/ssl_certificates_admin.php

Position "Create client certificate" button inside the form

---

.gitignore
interface/themes/style_light.css
interface/themes/style_tan.css

Fixes issue: #794 
Before:
After:

Flowboard input alignment

---

interface/main/messages/messages.php

Note: Also fixes 'Just Mine'
Fixes #799

Remove '>' next 'See All' in messages page, Reorganize html for clarity

---

.gitignore
interface/main/tabs/main.php
interface/patient_tracker/patient_tracker.php

The files described on commits had some untranslated strings. I used **xlt()** on all detected occorrences.
**No issue associated!**

Lack translation

---

interface/patient_file/summary/demographics.php

Fixes https://gitlab.com/librehealth/gci/issues/88
Before:
After:

Changed Demographics label from "Appointments" to "Future Appointments" fixes issue #722

---

.gitignore
interface/patient_tracker/patient_tracker.php

Before:
After:
The checkbox was repositioned to the settings option list. There is a hidden input there that probably should not be removed, I guess.
#783

Flowboard layout fix

---

interface/main/dated_reminders/dated_reminders_log.php

Task 4 in [https://docs.google.com/document/d/1fq4NG_rnjMDACjjlFAZ15tIid4Rp6QnSyFHB-uc7tH0/edit](url)
1.Startdate and enddate fields left aligned.
2.Space added between the refresh button and the table that appears below the refresh button on clicking it.

UI enhancement in messages->show reminders->view log 

---

interface/main/tabs/css/tabs.css
interface/main/tabs/templates/patient_data_template.php

Fix for #683
Gave encounter list div large z-index value

Fix: tab divider overlays encounter list

---

sites/default/menu_data.json

Rename Miscellaneous Tab Menu

---

library/globals.inc.php

Fixes #790
**Before:**
**After:**

Removes "Features" tab from User Preferences

---

modules/MIPS/measure_activate.php

Remove a duplicated 'Update' button in QA Measures -> Select Measures

---

interface/usergroup/ssl_certificates_admin.php

Moved the form into the div and changed the width
Fixes #806
Before:
====
After:
====

Made SSL Certificate Tab responsive

---

interface/themes/style.css
interface/themes/style_purple.css
modules/MIPS/measure_activate.php
modules/MIPS/truncate_reports.php

this is a cleanup for #811
hope this works

Cleanup (hope so): #811

---

interface/patient_file/report/custom_report.php
library/globals.inc.php
library/report.inc

Add the insurance company name to the demographics report #778

Add the insurance company name to the demographics report

---

library/globals.inc.php

Rename Flow Board under Calendar to "Patient Flow Board:"

---

interface/main/finder/dynamic_finder.php

Fixes #821 
The border was removed because it was the best solution and it was ugly (I hope the creator of this part is not reading this). I wrote a script that added bootstrap classes onto the fields because there was no other way.
jQuery always here to save the world.

Reorganized the page and added bootstrap

---

sql/1_0_1-to-2_0_0_upgrade.sql

Files that need to be added to the demo site.

Update Patch script for rel101 to rel 200, and deploy to demos sites

---

sql/1_0_1-to-2_0_0_upgrade.sql

Cherry Picked from master and merged with changes that were already in rel 200 release branch.

Merge upgrade script from master

---

INSTALL.md

INSTALL.md fixes #863

---

INSTALL.md
README.md

Clarifies some vague details and helps to address issues with XAMPP

Updating windows setup documentation

---

interface/patient_file/summary/add_edit_issue.php

Also reorganized code for better readability
Fixes #819

Added header for Popups->Issues->Add Issue popup

---

interface/main/finder/patient_select.php

This is a temporary fix till art can fix it with the pqrs stuff. It looks like he had an older version of the file. I used one from a Feb 2017 version of the code. This will fix #860

Temporary Fix for #860 Patient Search

---

Documentation/8_ForDevelopers/LibreEHR_Directories.md
sql_patch.php

Not sure how these  got put in but removing them

Cleanup naming

---

library/classes/InsuranceCompany.class.php
library/patient.inc
sql/1_0_1-to-2_0_0_upgrade.sql
sql/database.sql
templates/insurance_companies/general_edit.php
templates/insurance_companies/general_list.php
version.php

Deactivate an insurance company #848

Insurance inactivate.

---

sql/database.sql

Fix for new install

---

library/globals.inc.php

Fixes Issue #865 
@tmccormi 
@teryhill 
Also changed the "Disable Sql Admin Tool Link" to "Disable Sql Admin"
Thanks,
Jdew192837
Before:
===
After:
===

Disable sql admin

---

interface/forms/fee_sheet/new.php
interface/forms/misc_billing_options/new.php
interface/main/dated_reminders/dated_reminders_add.php
interface/main/dated_reminders/dated_reminders_log.php
interface/main/messages/messages.php
interface/themes/login.css
interface/themes/style_light.css
interface/themes/style_pdf.css
interface/themes/style_purple.css
interface/themes/style_tan.css
interface/themes/style_tan_no_icons.css

Fixes #838 
Hello!
Before (Messages):
===
After (Messages):
===
Before (Tab):
After (Tab):
Thanks,
jdew192837 (nulxis)

Add Bootstrap to Messages Tab

---

templates/documents/general_view.php

#939 
Idented the code and added missing styles.
Fixed the bug this way: _$file_ was replaced by _$this->file_ in all occurrences. _var_dump_'s showed me that _$this->file_ was the correct variable to use and _$file_ was null and that was causing the error
The log clearly says:
> Uncaught Error: Call to a member function get_id() on null in 
That told me that get_id() was being called in something null.
Thanks @pri2si17-1997 for the error logs, they were very helpful!

Patient documents display fix

---

interface/super/edit_globals.php
interface/usergroup/user_info.php

Fixes #887 
1 detail: the search button now has a float:right because bootstrap was creating a breakline between the input and submit button for some unexpected and unknown reason and it was ugly if the button stayed on the left side.

Organized & Idented code and bootstrap addition

---

library/api.inc

I corected path to globals.php in api.inc.
Fixes: https://github.com/LibreHealthIO/LibreEHR/issues/934

QA Measures - corrected path to globals.php

---

interface/forms/misc_billing_options/new.php

Add title to Patient/Client -> Visit Forms -> Misc Billing Options

---

interface/forms/ros/templates/ros/general_new.php

Partly #888
(Missing tab titles for a clinical form)

Add title to Patient/Client -> Visit Forms -> Review of Systems

---

INSTALL.md

I added instructions what is needed to change to run patient portal using Wamp.
Fixes: https://github.com/LibreHealthIO/LibreEHR/issues/921

Added  to install.md how to run patient portal using Wamp

---

interface/main/tabs/main.php
sites/default/sqlconf.php

Fixes #862 
Changed position of deactivating Frame Barrier to be called everytime at the end of activating Frame Barrier whenever mouse button is released after resizing.

Fixes bug of freezing when right most bar resized

---

interface/patient_file/problem_encounter.php
interface/patient_file/summary/stats_full.php
sites/default/menu_data.json

Before:
After:
Before:
After:
Fixes: https://github.com/LibreHealthIO/LibreEHR/issues/917

"Issues" -vs- "Medical Problems" - renamed

---

interface/forms/procedure_order/new.php
interface/super/edit_list.php

Changes for order type

---

interface/globals.php
interface/login/login.php

#946 
die() was triggered with a message saying that basically a login was required. I replaced it with a header to redirect the browser to login-page

replaced die() with an header for login page redirection

---

interface/globals.php

Fixed internal server error while login in globals.php

---

modules/MIPS/SQL/tests/PQRS_settings_config.sql
sql/2_0_0-to-2_0_1_upgrade.sql
sql/database.sql

Fixes #881 
- problem is solved by adding an extra column **usertext11** in `history_data` table.
You need to recreate your `history_data` table from `database.sql.`

Fix edit history patient bug

---

library/globals.inc.php

Changed field type to password

Changed field type to password

---

patient_portal/patient/libs/Model/DAO/PatientMap.php

Remove care team entry.

---

Documentation/8_ForDevelopers/Plugin-Development-FAQ.md

It was removed at some point in a cleanup ...

Add Lost Plugin Doc back

---

interface/usergroup/facility_user.php

Fix for unknown #982  The fix is in line 71 all else is refactoring by the editor

Fix for unknown

---

library/patient.inc

Sherwin Gaddis used this function and It will be used in the Order form
changes. #967 
I also included the suffix in the getproviders function.

Added a function that will give information for all insurances.

---

interface/reports/adjustments.php
sites/default/menu_data.json

This report gives a total for the selected adjustment code over a given time period. #443

Adjustment code report

---

interface/forms/soap/templates/general_new.php
interface/forms/soap/view.php

Fix to save and cancel form

---

interface/new/new_comprehensive.php

unable to add patient bug has been fixed

unable to add patient bug fixed

---

interface/login/login.php
interface/main/tabs/main.php

There is no libre favicon on both main and login page, both have been added in this patch

favicon has been added to login screen

---

interface/reports/immunization_report.php

[BUG]: Correct the span tag in immunization_report.php

---

interface/tags_filters/views/layouts/filters_layout.php
interface/tags_filters/views/layouts/patients_tags_layout.php
interface/tags_filters/views/layouts/tags_layout.php

Fixing tags, patient-tags, and filters ui format

---

interface/forms/procedure_order/new.php
interface/reports/immunization_report.php

IN Procedure_reort/new.php one P tag wasnt closed.

Closing the <p> Tag

---

sql/1_0_1-to-2_0_0_upgrade.sql

missing endif

---

sites/default/menu_data.json

Refer.php was a stub file intended to be used to link to something
called ReferCare.  This was a junk file that was removed, but the menu
item stayed.
REF: #937

remove Refer menu item

---

library/classes/InsuranceCompany.class.php
library/patient.inc
templates/insurance_companies/general_edit.php
templates/insurance_companies/general_list.php

I thought they were pushed in the commit for this, but it looks like
they were missed.

Not sure how these got missed

---

interface/main/finder/dynamic_finder.php
interface/new/new_comprehensive.php
interface/patient_tracker/patient_tracker.php
interface/reports/non_reported.php

Resolving the span Tag bug and Make changes in Search Patient ui

---

setup.php

favicon has been added to setup.php

favicon added to setup

---

interface/main/dated_reminders/dated_reminders_log.php
interface/patient_file/printed_fee_sheet.php

Fix to issue #825 
1.Print button moved up
2.Background color of print button has been changed to make it more consistent.
Before:
After
@Trodrige  I opened an issue and fixed it.Does this seem okay?

Print button prioritized in Reports->Blank Forms->Superbill  

---

interface/super/edit_globals.php
library/globals.inc.php

Removed un-used global This will close issue #749

Removed un-used global

---

interface/globals.php
patient_portal/home.php
patient_portal/patient/templates/_Footer.tpl.php

Added version number for portal to home page removed static version
number from footer.

Added version number for portal

---

interface/globals.php
interface/main/tabs/main.php
interface/super/edit_globals.php
interface/themes/style.php
library/globals.inc.php
library/headers.inc.php

- color picker experimental module converted to stable
- now user can pick primary and secondary color on any theme
screenshot below

color picker module added

---

interface/main/about_page.php

Added wiki site to the user manual. GCI issue #894

Added wiki site to the user manual

---

ccr/generatedXml/README
ccr/generatedXml/README.MD

fix for issue reported in GCI This was giving some console warnings. #961

fix for issue reported in GCI

---

interface/globals.php
patient_portal/home.php
patient_portal/patient/templates/_Footer.tpl.php
portal_version.php

I missed this file in the initial commit

Add version to portal

---

modules/calendar/find_patient_popup.php

- previously to find patients you need to click search button
- But now when you  type, patient list will appear.
- used  key up event with some modifications to improve ui

UI Improvement : messages>Add new > patient

---

patient_portal/account/account.lib.php
patient_portal/report/pat_ledger.php

Email Validation Function Updated, It choked at .io domain before now it doesn't.

Fix for #1066 Email Validation Functions

---

interface/orders/procedure_provider_edit.php

validation for selection boxes has been added.

validation for selection boxes under providers.

---

interface/patient_file/report/patient_report.php
interface/patient_file/summary/stats_full.php
interface/patient_file/transaction/transactions.php
interface/reports/pat_ledger.php
templates/documents/general_list.php

Fixes #414 
Added "Back To Patient" button on Report | Transactions | Issues | Ledger, on demographics screen for patient.
Preview:
Report
Transactions
Issues
Ledger
Questions:
- Transaction screen has a "cross"/close button and it opens as a window over demographics screen. I think there is no need to add button here or if added, it should close the transaction window? 
Preview:
- I didn't add the button to Documents because there is also another way to go to Documents screen, the 'Misc. > New Documents' route. So should there be something which checks which route user took and then add the button?
One way to see the changes _locally_ would be as follows:
1) Clone my repo via `git clone https://github.com/apooravc/LibreEHR.git`
2) After cloning, only the master branch would be available …

Fix #414: 'Back to Patient' button on screens linked from demographics

---

patient_portal/account/account.lib.php

fixes #1077 
Readability improvement on if user isNew() function. 
@teryhill take a look 👍

Readability improvement on check if user isNew()

---

patient_portal/account/account.lib.php

fixes #1076 
Update for patient id generator function
@teryhill  take a look 👍

Update for patient id generator function

---

library/globals.inc.php
modules/calendar/add_edit_event.php

Fixes #1071 
Added a check for user selected time (taking AM/PM into account) to be within clinic hours. The check would alert the user and prevent the appointment from being made otherwise.
One way to see the changes _locally_ would be as follows:
1) Clone my repo via `git clone https://github.com/apooravc/LibreEHR.git`
2) After cloning, only the master branch would be available locally. Enter `git checkout -b check-cal-event origin/check-cal-event` or `git branch check-cal-event origin/check-cal-event` to get the branch _check-cal-event_ locally.
3) The changes could then be seen on Calendar screen.
@teryhill Please have a look.

Fix for #1071: Calendar events need to respect clinic hours

---

modules/util_dupecheck/index.php

Query error due to DOB column being called dob.
dob>DOB for everything in file for full consistency

Dupecheck incorrect column name for DOB

---

custom/chart_tracker.php
interface/batchcom/batchcom.php
interface/main/display_documents.php
interface/orders/list_reports.php
interface/orders/load_compendium.php
interface/orders/orders_results.php
interface/orders/procedure_provider_list.php
interface/orders/types.php
interface/patient_file/summary/labdata.php
interface/patient_tracker/patient_tracker.php
interface/reports/patient_edu_web_lookup.php
interface/super/edit_globals.php
interface/super/manage_document_templates.php
interface/themes/style.php
interface/usergroup/addrbook_list.php
interface/usergroup/user_info.php
templates/documents/general_upload.php

@teryhill  this is progressing phase of the ui refactoring
team have a look at this @2208Abhinav  @apooravc  and make the changes
Make sure you include the headers.inc.php which contains the color picker controller.

ui refactoring  : part 1 - procedures

---

interface/billing/billing_report.php
interface/billing/edih_view.php
interface/billing/sl_eob_search.php
interface/forms/fee_sheet/new.php
interface/forms/fee_sheet/review/initialize_review.js
interface/patient_file/encounter/forms.php
interface/patient_file/front_payment.php
interface/reports/pre_billing_issues.php

Doing work similar to #1092 for fees section.
Following buttons are not covered yet:
css_button class which is already added trumps the cp-classes in CSS preference in following:
Pre-billing issues --> submit buttons
fee sheet --> encounter summary --> delete/edit/esign buttons
WIP (unconventional behavior):
edi history --> Choose files button
fee sheet --> administrative --> review button
batch payments buttons

ui refactoring : part 2 - fees

---

modules/calendar/index.php

changing text color

---

interface/main/finder/dynamic_finder.php
interface/patient_tracker/patient_tracker.php
library/globals.inc.php

Am sure this should remove the open in new window functionality
Open for feedback

removed the open in new window functionality #1088

---

interface/login/login.php

login button fixed

---

interface/main/tabs/templates/user_data_template.php
interface/usergroup/user_info.php
interface/usergroup/usergroup_admin.php
interface/usergroup/usergroup_admin_add.php
sql/2_0_0-to-2_0_1_upgrade.sql
sql/database.sql

@teryhill done, need some info on how to add this to menu

Profile picture feature for users

---

CONTRIBUTE.md

How to setup git/github to start contributing

How to contribute to github

---

sites/default/menu_data.json

Installer/ SQL updater menu item for MIPS QA module.

Installer to menu

---

sql/2_0_0-to-2_0_1_upgrade.sql
sql/database.sql

Fix for cancellation reasons

---

library/gen_x12_837.inc.php

Fix for the onset dated code #1121

Fix for the onset dated code

---

library/globals.inc.php
modules/calendar/includes/get_provider_events.php

This will display the status colors for the appointments unless the
status is None in which case it will display it in the appointment
category color.

Added the ability to display the status colors

---

modules/calendar/add_edit_event.php
sql/2_0_0-to-2_0_1_upgrade.sql
sql/database.sql
version.php

Clean up the code for the next set of changes #1141

Clean up the code for the next set of changes

---

interface/billing/billing_report.php
interface/billing/print_daysheet_report_num1.php
interface/billing/print_daysheet_report_num2.php
interface/billing/print_daysheet_report_num4.php
interface/forms/fee_sheet/new.php
library/globals.inc.php

Added user names to the eod reports, set them to look at the encounter
provider (helps eliminate provider 0 issues) added payment type. Added a
4th report that keys off a user field in the fee sheet and gives a total
for the user that did the fee sheet. #1143

Changes to EOD reports

---

modules/calendar/add_edit_event.php

This fixed some recurring errors. Removed a couple of commented out
lines of code. Added logic to create out of office based on the ending
time for in office. Fixed code so that days of the week works correctly
with the check box.

This fixed some recurring errors.

---

library/formsoptions.inc.php

Adding a means to check if a form is active. This function checks to see
if the sql file (table.sql) has been run and it checks to see if the
form is enabled in forms admin. #1167

Adding a means to check if a form is active

---

modules/calendar/add_edit_event.php
modules/calendar/find_patient_popup.php

Added back the ability to create a patient from the calendar. This was
in the version before we upgraded the calendar just added it back. #1169

Added back the ability to create a patient

---

modules/calendar/index.php

Fixes #1145 
@aethelwulffe Attempted a refactoring of UI of facility list according to old look you mentioned. Also added an overflow property with a max-height, hence the scrollbar.
Preview with this commit:

Fix for #1145: Refactor facility list in calendar

---

library/gen_x12_837.inc.php

Made the entry 096 as opposed to 96. This needed to be 096 to be correct.

Fix error in file

---

interface/main/tabs/templates/user_data_template.php

Bad relative path, bad filename (case-sensitive).

Menu tabs user_data_template error

---

sql_patch.php
sql_upgrade.php

no "public" directory exists.  Probably from some composer implementation.  dunno.  Fixed.

Favicon.ico 404 errors

---

interface/orders/types.php
interface/orders/types_ajax.php
interface/orders/types_edit.php
library/options.inc.php

Small UI revamp for the procedures/orders configuration screen. 
Changes: 
- Changed table and button style of base page
- Change modal/dialog box usage to iziModal
- Added some validation rules for the creation and editing of procedures
To-do: 
- Explanations of form elements so as to make it easier for the user to understand what information they need to put in
- Override default page CSS with bootstrap CSS to change button designs in the modals
Screenshots:

Procedures process UI update

---

library/globals.inc.php
modules/calendar/includes/get_providers.php

Added another provider display option for the calendar. Last name first
initial. #1184

Added another provider display option

---

interface/patient_file/report/patient_report.php

Uses accordion to make the patient reports cleaner.

MigDinny patient_report accordion

---

templates/insurance_companies/general_edit.php

added the 2 missing echos #1192

added the 2 missing echos

---

sites/default/statement.inc.php

Statement download name change from the old file to libreehr

Statement download name change

---

library/globals.inc.php

Was getting warnings in error log with php 7

changed the +'s to .'s

---

interface/patient_file/summary/demographics.php
interface/tags_filters/start.php
library/globals.inc.php

Started coding the ability to completely turn off tags. #1229

Started coding the ability to completely

---

updater/lib/updater_functions.php

fixes a bug which causes folders to appear as files in updater download module

fix for folders with dot causing bug in updater

---

interface/main/tabs/templates/user_data_template.php

repair relative link

---

library/encounter_events.inc.php

Fix for the autocreate encounters #1265

Fix for the autocreate encounters

---

interface/reports/clinical_stats_by_demographics_report.php
interface/reports/lab_stats_by_demographics_report.php
interface/reports/username_report.php
library/ajax/clinical_stats_and_lab_stats_by_demographics_report_ajax.php

Updates to two of the new reports for NHanes and general use.

Fix to Diagnosis search and Add Age Range Filters

---

interface/patient_file/summary/demographics.php

This Pr fixes issue #1223 by doing the extension check

Extension check, fixes #1223

---

interface/main/finder/dynamic_finder_ajax.php

Added error check against the table fields #1277

Added error check against the table fields

---

WINDOWS_INSTALL.md

Added Windows Install File. Took information from INSTALL.md file and added changes. #1288 includes INSTALL.md changes, but those are not included in this PR.

Added Windows Install Markdown File Separate of INSTALL.md

---

interface/batchcom/batchcom.php

This PR fixes #1243 .
@aethelwulffe have a look

Fix : BatchCom Tab not displaying

---

interface/patient_file/encounter/new_form.php

Fix #1296: Dropdown no longer hides behind content

---

modules/MIPS/measure_activate.php

**Link**: QA Measures->Select Measures
**Work**: Let “Update” and MIPS specialty… be on one row
- Change the background of all measures
- Delete one update button
**Changes**: 
- Added bootstrap rows to structure the form. The checkboxes were broken to start with.
- Deleted one Update button.
- Changed colour of all measures
**Before**: 
**After**:

Fix: Select Measure Style

---

interface/forms/physical_exam/edit_diagnoses.php

Use a Prepared Statement to prevent SQL Injection.
Fixes #1380

Fix #1380: SQL Injection vulnerability

---

interface/new/new_comprehensive.php

feat: iziToast replaces browser alerts

feat: iziToast replaces browser alerts

---

interface/reports/pat_ledger.php

Back Button Added to Ledger

---

interface/forms_admin/forms_admin.php

The forms were quite hard to look at to start with, I added some bootstrap styling to the table and the surroundings to make it more organized.
Task 20
Link: Admin->Other->Form
Work: Style the whole page, horrible mix of colors here, centralize fields(Already open issue)

style: form administration tables

---

interface/usergroup/user_admin.php
interface/usergroup/usergroup_admin.php

Added Profile Pictures on updating users.
Fixes #1368

fix #1368: profile pictures on update user

---

interface/patient_file/front_payment.php

**Link:** Fees->Payment
**Work:** - Put buttons immediately under the form
**Changes** - The buttons are now under the form rather than under the table
**After Changes**

fix: button change to under form

---

interface/orders/load_compendium.php

**GCI: Task 11 in EHR UI Grab Bag**
Link: Procedures->Load compendium
Work: - Put fields in a form with a header

UI Fix: Load Lab Configuration Form Styling

---

interface/main/tabs/main.php

Fixes #1302 
Fixed it so that it no longer stays up forever once the mouse moves 50px away from it.

Fix :FAB doesn't close when cursor moves away

---

interface/main/tabs/css/tabs.css

Used the same fix as MigDinny did in his issue.
Fixes #1308

Fix #1308: Encounter Menu Content Blocking Dropdown

---

interface/patient_file/encounter/new_form.php

Changed onClick to onmouseover for menu items in encounters.

Fix #1292: Encounter Tabs Now Dropdown Upon Hover

---

interface/main/tabs/templates/user_data_template.php

Fix: Admin Title no longer obstructs nav 

---

index.php

I had to create a new fork, as I couldn't go back three commits (I don't know how). This improves code quality of `index.php` and proves I set up my development environment 😄

Fixed the sqlconf.php issue

---

interface/patient_file/summary/demographics.php

Added `<span></span>` to button so that the other side of the button would show up according to the css files. Deleted `btn` class and added `iframe` class for consistency with the 'Delete' button's classes that's right beside it on the page.
Also deleted unnecessary end tags `</b></form>`

Fix #1295: Add/Edit Profile Picture Button Not Well Displayed

---

interface/super/show_groups_popup.php

@muarachmann @robbyoconnor , I attempted a re-fix for this issue, please review

fix authenticated sql injection #1215

---

interface/new/new.php

When i attempt to delete this PHPstorm shows me its usage in `new_patien.php` and `new_patient_save.php`. But i dont think it is actually ever used.

deleted useless file

---

interface/main/messages/messages.php
interface/main/tabs/edit_roles.php
interface/patient_file/summary/add_edit_issue.php
interface/patient_file/summary/stats_full.php
interface/roles/role_create.php
interface/usergroup/facilities.php
interface/usergroup/facility_user.php
interface/usergroup/usergroup_admin.php
interface/usergroup/usergroup_admin_add.php
library/dated_reminder_functions.php

Recreating mua's lost #1207 branch.  That repo was deleted, and had merge conflicts.
Ten file changes, with lots of stuff in odd places. @muarachmann please very very carefully review these changes and ensure we are not stomping on any commits made since these changes, as I was forced to directly copy each individual file.  Blame for commit time status should be looked at if there is any question for any of the changes.  Please verify the contents of each file.

izi admin recreate from #1207

---

interface/billing/era_payments.php
interface/billing/new_payment.php
interface/billing/payment_master.inc.php
interface/billing/search_payments.php

UI Fix: Batch Payments Form Styling

---

interface/usergroup/adminacl.php

Link: Admin->ACL
Work: - Make “Advanced” a button
- Make “Edit”, “Add New Group”, and “Remove Group” buttons.

style: added button styling in ACL

---

interface/orders/orders_results.php
interface/orders/types.php
interface/orders/types_edit.php

Changes made:
-> Ported the find-procedure popup to iziModal style.
-> Fixed the cancel button.
-> Save button name changed to Refresh.

Solved issue #1361

---

modules/MIPS/clinical_measures.php

Fix:#1415 - Validation of dates done

---

templates/pharmacies/general_edit.php

1.changed the email input type from 'text' to 'email'.
2.validated filled email entry input to check fo validity using javaScript regex pattern match before saving.
3.displayed messages to users with iziToast

Solved issue #1413 

---

interface/orders/orders_results.php
interface/orders/types.php

These are some changes that I had to make to the last PR.
Changes :
->Removed old junk of popup style iframe function sel_proc_type()
->Added xlt() function to izimodal title and subtitles

Added changes to closed PR #1410

---

interface/super/rules/controllers/alerts/view/list_actmgr.php
interface/super/rules/controllers/browse/view/list.php
interface/super/rules/controllers/browse/view/plans_config.php
interface/super/rules/controllers/edit/view/action.php

@muarachmann Added this new PR instead. The links in the PHP files were broken #1299.

Fix: Broken links #1299

---

modules/MIPS/report_results.php

removed the html row of the where the delete button belongs to when ajax returns success so as to sync backend with front end code.

Solved #1429 Deleting Reports can not be determined if successful or not until page is refreshed 

---

modules/MIPS/generate_MIPS_xml.php

Fix : #1418
Changes made in modules/MIPS/generate_MIPS_xml.php.
Fixed the iframe by adding background-color.

Fix:#1418 Fixed the modal box

---

interface/reports/lab_stats_by_demographics_report.php
library/ajax/clinical_stats_and_lab_stats_by_demographics_report_ajax.php

Fixes #1281 
@tmccormi try this PR, i hope it almost solved the issue.

pagination on server side, fixes #1281

---

interface/patient_file/summary/appointment_log.php

Fix:Two Close Button on Modal #1460

---

interface/patient_file/summary/demographics.php
library/sanitize.inc.php

fixes issue #1401
make variable names more descriptive
create functions for common tasks
@robbyoconnor @aethelwulffe

fix authenticated user unrestricted file upload on profile picture edit

---

sites/default/filemanager/assets/css/dropzone.css
sites/default/filemanager/assets/css/styles.css
sites/default/filemanager/assets/js/dropzone.js
sites/default/filemanager/assets/js/script.js
sites/default/filemanager/index.php
sites/default/filemanager/scan.php

Fixes #1311 
Fixed the abrasive colors on the file manager page and did some small changes to the UI.
See before and after below:

Fix #1311: File Manager Page Styling

---

interface/billing/edih_view.php
interface/forms/patient_encounter/common.php
interface/forms/soap/C_FormSOAP.class.php
interface/forms/soap/templates/general_new.php
interface/main/authorizations/authorizations.php
interface/main/finder/dynamic_finder.php
interface/main/finder/select_patient.php
interface/main/messages/messages.php
interface/main/tabs/edit_menu.php
interface/new/new_comprehensive.php
interface/orders/pending_orders.php
interface/orders/procedure_stats.php
interface/orders/types.php
interface/patient_file/encounter/superbill_custom_full.php
interface/patient_file/history/encounters.php
interface/patient_file/problem_encounter.php
interface/patient_tracker/patient_tracker.php
interface/super/edit_globals.php
interface/usergroup/addrbook_list.php
interface/usergroup/docs_validation.php
interface/usergroup/facilities.php
modules/MIPS/import_data.php
modules/MIPS/mips_installer.php
modules/MIPS/reset_provider_to_unassigned.php
modules/MIPS/update_data.php
modules/calendar/admin.php
modules/calendar/index.php
templates/practice_settings/general_list.php

@tmccormi fixed #1286 for flowbard menu take a look so i can go through all the menu

Fix : Themes not consistently implemented #1286

---

interface/reports/reports_controllers/SalesByItemController.php
interface/reports/sales_by_item.php

@aethelwulffe @muarachmann  I succeeded to make this fix kindly review and give me feedback.
After inputting selecting desired drop down menu options and clicking submit, results are shown as needed

Solve #1438 MySQL errors showing up in search submission

---

interface/patient_file/pos_checkout.php

**GCI: Task 9 in EHR UI Grab Bag**
Link: Fees->checkout
Work: - Style the receipt -Make “Print” … buttons blue(default) -Add “Back” button

UI Fix: Checkout Receipt Styling

---

updater/ajax_user_mode.php
updater/lib/api.github.php
updater/lib/updater_functions.php
updater/updater.php

logic mistake got fixed
- WIP : to improve the performance

Patch : fixing updater logic

---

interface/patient_file/summary/demographics.php

Solved #1449: Strange Filenames and extensions Showing alongside ID Card

---

library/classes/Installer.class.php

Disabling the report generator due to install errors.  .env file related stuff in library/installer.class.php cause the stuff to break.  Testing a full install now, and will merge once fixed.  Code did not affect existing installations.

Report generator disable

---

interface/reports/reports_controllers/ClinicalController.php

1. made sure submitted form inputs where available to function preparing sql query `prepareResults()`.
2. made sure `$sqlBindArray` variable was not only accessible in 'if' statements.

Solved  #1461: Can Not Filter Patient Clinic Reports

---

interface/forms/track_anything/history.php

This fixes the referenced issue #1462 @Ngai-E can you test this. @aethelwulffe i think i made the fix here is what i get.

Fixed history tracking form #1462

---

interface/patient_file/printed_fee_sheet.php

FIX #1507 Remove Print button from Superbill/Fee sheet

---

interface/usergroup/addrbook_edit.php

Duplicate Fields removed in Addr Book.

Fixed Issue #1520 -Duplicate fields in addr book

---

interface/themes/style_tan.css

Set the text color inside button to white when it is visited or hovered 
Closes #1530

Unreadable text on the submit button #1530

---

interface/forms/education/info.txt
interface/forms/education/new.php
interface/forms/education/report.php
interface/forms/education/save.php
interface/forms/education/table.sql
interface/forms/education/view.php
sites/default/sqlconf.php

Ok i have redesigned this @muarachmann  hope this is better.

Education form

---

assets/js/DataTables-1.10.16/datatables.css
interface/reports/clinical_stats_by_demographics_report.php
library/headers.inc.php

The reported console errors no longer show when the “Clinical Statistics: Demographics vs. Diagnosis” and “Clinical Statistics: Demographics vs. Lab Results” Reports load.

Solves Issue #1549 : fixed img urls & handled msie error

---

.gitignore

This should fix the defaults sqlconfig file from being tracked by git

updated gitignore file to exclude sqlconfigs

---

interface/globals.php

closes https://github.com/LibreHealthIO/lh-ehr/issues/1553

Fixed URL for js modules

---

interface/patient_file/summary/stats_full.php

removed '_' in modal title for medical_problem

---

modules/report_generator/yarn.lock

- Fixed vulnerabilities via dependencies
Signed-off-by: Mua Rachmann <muarachmann@gmail.com>

Updated deps for report generator

---

interface/super/edit_globals.php
interface/themes/style.php

I have done the fix on the issue #1536.

White space present at top right on menu

---

interface/main/tabs/css/tabs.css

Fixed height for chrome browser
@maggienegm , @Ngai-E please test this and let me know

:bug: Bug fix

---

interface/login/login.php

Height of the language field was smaller as it was not showing full text "g".
The field of language was not having border which is uneven.

Field size increased & border added

---

interface/patient_file/letter.php

remove illegal characters in filename passed by user.

fix authenticated unrestricted file write in letter.php  actions

---

templates/documents/general_view.php

I used the existing HTML entity encoding functions in htmlspecialchars.inc.php to prevent XSS attacks in the Notes section.

Added HTML entity encoding to notes to prevent XSS

---

interface/batchcom/batch_reminders.php
interface/billing/billing_report.php
interface/forms/track_anything/history.php
interface/login_screen.php
interface/patient_file/history/history.php
interface/patient_file/history/history_full.php
interface/patient_file/history/history_save.php
interface/patient_file/history/history_title.php
interface/patient_file/history/patient_history.php
interface/patient_file/history/track_appointments.php
interface/patient_file/reminder/active_reminder_popup.php
library/classes/Controller.class.php
setup.php
updater/updater.php

Xss updates
