library/pnotes.inc

LIKE comparisons result in duplicate messages sent to and from different
providers.  Other weaknesses may be apparent with LIKE `pid`.  Further
investigation needed...or just a much more modern message tool!

pnote_user_fix

---

interface/forms/patient_encounter/common.php

Billing Facility and Facility are really poorly understood by users.
This naming convention is responsible for a lot of confusion and billing
failures. 
The only quandary is what to do to ensure that the Place of Service is the Location Code source.  I have seen this one tiny change help several businesses get things together.

Change Facility to Place of Service

---

library/billing.inc
sql/database.sql

#167 claims table uses a triple primary key with encounter, pid and an
autoincrement of 'version' integer.
Updating seems to only happen via billing.inc and only when the
$newversion flag is set.  Testing to follow.

claims table autoinc triple key innodb failure

---

sites/default/menu_data.json

Erased the menu item for managing zend modules. #178

remove module from tab menu

---

interface/main/calendar/add_edit_event.php

#236 This addresses the issue of trying to add +1 to a NULL value, but might
be better served by just re-establishing autoincrement in the INNODB
table like we did for the others.

calendar_autoinc hack extension for INNODB

---

interface/usergroup/facilities.php
interface/usergroup/facility_admin.php
library/Claim.class.php
sql/0_0_1-to-1_0_0_upgrade.sql
sql/database.sql
sql/libreehr_upgrade.sql

Uses the legal business entity name in EDI, letting the users call their
facilities other names that identify the location code, such as "Office,
Home, ALF, Hospital, etc...".
This corrects a lot of trouble, and should be added to the CMS-1500 code as well.
The decision to use alias instead of altering the behavior of name was due to extent of it's use, and there is a reasonable argument for that in any case.

Add Legal Business Entity Name to Facilities

---

interface/main/calendar/add_edit_event.php
library/patient.inc
library/patient_tracker.inc.php

I added do_action() hooks so custom behavior can be added when: an appointment is saved, a patient is saved, the appointment status is changed on patient tracker.

Hooks for appt and patient save and patient tracker appt stautus change

---

library/globals.inc.php

This is the hook that allows for globals to be dynamically added by a plugin. At some point it got removed, probably by a conflict-resolving merge.

Returned globals init hook that got removed

---

interface/patient_tracker/patient_tracker.php

fixed an inconsistency reported by HT. in every other instance the word
Category is used except on the main PFB screen it is called visit type,
changed it to category to be in line with the code base #423

fixed an inconsistency reported by HT

---

interface/tags_filters/views/tags_demographics.php

Fixes #405 
I think the demographics page can be further refined by modifying the `expand_collapse_widget` function to accept an array of Buttons and using that for the tags and other stuff in the future.
Also, I noticed a tiny bug: When you have no tags and you click on "Add" and then "Cancel", the "No tags found" message disappears. It's replicable on the online demo. Not sure if there's an issue already created for it.
Thanks!

Add collapsing behaviour to tags in demographics

---

library/globals.inc.php
library/options.inc.php

Fixes #439 
A limitation of this code is that it assumes all formatting options to be added in the future to be in `3 3 4` , i.e, US format. An advantage of this is that people can add new formats by just including it in the `globals.inc.php` file. If need be, I can expand this code for the general case, but that model would require extra effort for people using the system to add new formats (since they'll have to write regex). Opinions?
The check for phone numbers is done (for now) using layout_options.edit_options value
EDIT: Please check lines 829-842 of global_inc.php and lines 1705-1715 of options_inc.php for the diffs

Add phone number formatting

---

library/classes/Installer.class.php

" --opt --quote-names -r $backup_file " .
//" --opt --skip-extended-insert --quote-names -r $backup_file " .
Comment out above line and enable this to have really slow DB
duplication.
This change speeds up cloning of the database for backup or launching a
new site from a template DB by a factor of about 600.
This is used in production, and has launched ~45 production sites dependably.

Database cloning Turbo Mode

---

interface/forms/fee_sheet/new.php
interface/forms/patient_encounter/common.php
interface/forms/vitals/templates/vitals/general_new.php
interface/globals.php
interface/main/messages/messages.php
interface/new/new_comprehensive.php
interface/patient_file/encounter/forms.php
interface/patient_file/history/encounters.php
library/headers.inc.php

I tried hard to keep the frames as responsive as possible. 
This PR attempts to improve UI over following screens::
1. Encounter Summary
2. New Encounter Form
3. Encounter History
4. Vitals
5. Fee Sheet
6. Message and Reminder

UI improvements in Encounter Screens 

---

interface/forms/fee_sheet/new.php
interface/forms/patient_encounter/common.php
interface/patient_file/encounter/superbill_custom_full.php
interface/super/edit_globals.php
interface/usergroup/addrbook_list.php
interface/usergroup/facilities.php
interface/usergroup/facility_user.php
interface/usergroup/usergroup_admin.php
patients/messaging/messages.php
templates/document_categories/general_list.php
templates/document_categories/general_upload.php
templates/documents/general_list.php
templates/insurance_companies/general_edit.php
templates/insurance_numbers/general_edit.php
templates/pharmacies/general_edit.php

Just minor changes here and there. Smaller Input Boxes and layout issues.

General cleanup, minor bug fixes and UI improvements in Administration

---

setup.php

discovered by bclee
quote: " Just to clarify WHY this change is being made:
requiredDirectory1 and requiredDirectory2 were setup to make sure
permissions were set correctly for old calendar directories. These
directories no longer exist. The setup script complains and stops
because the directories '' and '' were not writable. Those are null
strings. These variables were commented out, but needed to be removed
from the list of directories that get checked."

setup broken by missing old calendar

---

library/globals.inc.php
sql/database.sql

Adding a clinical_rules stub table to database.sql to get rid of error
in code looking for custom patient-level rules when the MIPS tables have
not been installed.

Adding clinical_rules

---

INSTALL.md
README.md

I've added what should you do if you don't find "sql-mode" parameter in my.ini file (README.md and INSTALL.md) and I added the missing piece of text (INSTALL.md):
"sql-mode = STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
or sometimes it maybe sql_mode"

Windows Installation Docs: Added "If you don't find the sql-mode in my.ini"

---

interface/main/tabs/js/tabs_view_model.js

Fixes #850 
Open 2 tabs >> lock one >> close the other >> the one which is locked remains locked with plenty of space available. Now, after closing the other tab, the locked one unlocks.

Unlocking locked tab when it's the only one there

---

interface/patient_tracker/patient_tracker.php

Now the refreshing feature will only refresh the flowboard if settings aren't opened.
Nothing else to add.
Fixes #831

Flowboard >> page isn't refreshed anymore when settings are opened

---

interface/billing/sl_eob_search.php
library/globals.inc.php
sites/default/statement.inc.php

Print insurance company name on statement instead of "Insurance information on file". I am working on the not printing the statements based on insurance company and thought this would be a good addition.

Print insurance name on statement

---

README.md

I deleted duplicated colon in readme.</br>

Deleted duplicated colon in "windows" header - README

---

interface/main/tabs/templates/tabs_template.php

Now the locked tab has the new buttons.
This is a thing that was apparently lacking in #777

Forgot to add those buttons to the locked tabs

---

library/clinical_rules.php
library/globals.inc.php
modules/MIPS/SQL/1_INSTALL/PQRS_billingcodes.sql

1.  Provides default date global for direct entry encounters when in
reporting mode (to be implemented later).
2.  Removes (temporarily) clinical rules check for Medicare.  This may
be required conditionally for 2018 MIPS standards.

MIPS Medicare Update

---

interface/forms/procedure_order/new.php
interface/patient_file/report/custom_report.php

Logo was not previewed in the printable version of report
Before
Now
As you can see I have reduced the size of image to 56px by 45px because without this the result was

Solution for missing logo in printable versions of reports issue #962

---

interface/main/tabs/templates/tabs_template.php

Fixes #882 
Removed the refresh icon from tabs when in locked/ hidden state.
Tabs UI when locked:
Tabs UI when unlocked:
@aethelwulffe @teryhill Please have a look.

Fix for #882

---

interface/billing/sl_eob_search.php
sites/default/statement.inc.php

Fixes #858 
Added a GLOBAL variable `$GLOBALS['stmts_below_minimum_amount']` to keep count of ignored statements having amount value less than `$GLOBALS['minimum_amount_to_print']`. This reason along with number of ignored statements are logged to user at end of `$STMT_TEMP_FILE` after all the `make_statement` calls are done.
One way to see the changes _locally_ would be as follows:
1) Clone my repo via `git clone https://github.com/apooravc/LibreEHR.git`
2) After cloning, only the master branch would be available locally. Enter `git checkout -b log-reasons origin/log-reasons` or `git branch log-reasons origin/log-reasons` to get the branch _log-reasons_ locally.
3) The changes could then be seen on Fees/Posting page.
@teryhill Please have a look.

Fix for #858: Log the reasons statements did not print. 

---

interface/super/edit_globals.php

Fixes #242 
When the user clicks on save, and the edit_globals iframe is refreshed, there is no notification given to users. This PR adds a notification shown below which fades out after `3 seconds`:
Works on the value of `$_GET['unique']` which is `null` on first opening edit_globals or refreshing it by clicking on refresh icon. It becomes equal to `yes` after clicking on save button.
@aethelwulffe @teryhill Please have a look.

Fix for #242: Notify when globals saved

---

library/patient_tracker.inc.php
modules/calendar/add_edit_event.php
sql/database.sql

Issues which this PR deals with:
1) When user selects "Deleted" status and saves, status is logged but the appointment isn't deleted off calendar.
2) When user clicks on delete in add-edit-event panel, appointment is deleted off calendar but it is not logged in patient-tracker and patient-tracker-element tables.
Status "Deleted" is added in database.sql file. 
@teryhill This first commit attempts on addressing 2nd point. Currently, the issue with it is that "event_date" is passed as NULL upon clicking delete to manage-tracker-status which makes the control flow to go into block at line 204 instead of block at line 218 in patient_tracker and it results in 2 inserts (one in each table) made when clicking delete with one NULL apptdate value coming up in patient-tracker table instead of one …

Logging appointment delete in calendar

---

interface/billing/sl_eob_search.php

Ported from MigDinny's branch.
This addresses a case where nothing is selected, but someone tries to create a statement pdf anyway...and an error can be created.

migdinny fee posting error fix

---

modules/calendar/index.php

Fixes #791 
A patient event slot in calendar has it's title (name) inside a `div` element with class `fc-title`. Using [eventRender](https://fullcalendar.io/docs/eventRender) which is triggered when an event slot is being rendered on calendar, all such patient slots/events (having `pid != 0`) can be selected, and their titles can be converted into corresponding links to patient's demographics. 
Thus, when the title link is clicked, demographics tab would open of corresponding patient, with their information displayed in patient data area (on upper-left and upper-right sides). If any other area is clicked in event slot, then calendar event panel would open, which is default behavior.
@teryhill @pri2si17-1997 Attempted a fix for this, please have a look. There is one issue with the opening …

GSoC 2018 :  Calendar Improvements-Hyperlink the patient name

---

modules/calendar/add_edit_event.php

Added an alert so that users can be sure when deleting patient appointments by selecting status "Delete" and clicking save in event panel. Please have a look @teryhill

Add status delete alert in patient event panel

---

sql/2_0_0-to-2_0_1_upgrade.sql
sql/database.sql

Special characters were used instead of normal single quotes in sql files.  passive fail on upgrades.
Noted during testing that the database menu inserts re-run no matter if they were done or no.   I think that was intended behavior though.

Calendar Cancellation Reasons sql fix

---

modules/calendar/includes/get_provider_events.php
modules/calendar/index.php

Added event description text after hyperlink name in a Calendar event slot. With this, only clicking on hyperlink would open demographics tab and clicking on anywhere else would open event panel. @teryhill Please have a look.

Adding event description after hyperlink

---

interface/super/edit_globals.php

Fixes #1162 
Some of the global fields in Administration > Calendar section were not saving changes. Corresponding updates were not taking place in DB. After examining where flow of control went while program was running, it was found that solving the issue required a couple of syntax changes in the _elseif_ chain in validation block from line `258` to `309`.  @teryhill Please have a look.

Fix #1162 Not able to change fields in globals

---

interface/super/edit_globals.php

Making Calendar refresh itself whenever a change to it is done, either from inside or outside Calendar. This covers the case when a Calendar global in `Admin > Globals > Calendar` is changed and saved with Calendar tab also being open along with  _Edit Global Settings_ tab. @teryhill Please have a look.

Admin based calendar refresh

---

interface/usergroup/user_admin.php
modules/calendar/add_edit_event.php

@teryhill Attempted a fix for schedule facilities, please have a look.
There is a global `$GLOBALS['restrict_user_facility']` in features tab in Admin which when true restricts Facilities in calendar event panel to only selected schedule facilities set up in Edit User for selected(clicked) user(provider) in calendar. If the global is true, and user selects `facility 1` & `facility 2` in Schedule Facilities and `facility 3` in Default Facility in Edit User, then after saving changes, only `facility 1`, `facility 2` & `facility 3` would show up in Facility in calendar event panel for that user(provider). Otherwise, when global is false, all facilities which have non-zero `service_location`, i.e., facilities which have _service location_ checked will show up in calendar for that user. …

Fix calendar schedule facilities

---

sites/default/menu_data.json

Trying to open "Search or Add Patient" tab by going main menu > Patient/Client > Add New/Search results in following blank tab to open:
It happens because link to this tab isn't updated in menu_data.json while changing tab's file from `interface/new/new.php` to `interface/new/new_comprehensive.php` in #1173. @aethelwulffe Please have a look.

Update menu patient add/search link

---

interface/globals.php
interface/super/edit_globals.php
library/globals.inc.php
library/patient_tracker.inc.php

This PR adds a global `calendar_timezone` which the user could use to select his/her time zone for Calendar date/time functions. [date_default_timezone_get](http://php.net/manual/en/function.date-default-timezone-get.php) (used as default time zone for Calendar) gets the value of `date.timezone` in php.ini file if it is valid/supported (valid time zones given [here](http://php.net/manual/en/timezones.php)) otherwise defaults to UTC. The user selected time zone from Main globals or User specific globals (given more preference when different values) is set as `date.timezone` configuration option value using [ini_set](http://php.net/manual/en/function.ini-set.php). 
`date` function is used to fill entries in `date` & `start_datetime` columns in patient_tracker and patient_tracker_element …

Set Calendar time zone 

---

interface/main/tabs/templates/tabs_template.php

If you inspect element on @naveen17797 's updater-icon, you can see the `<i class="fa fa-refresh"></i>` which is used for updater button's icon from font awesome library. Now, the tab refresh icon element is `<span class="fa fa-refresh tab-button" data-bind="click: tabRefresh" title="Refresh"></span>`. They both have common class fa-refresh because they both have same refresh type icon.
So, when we close iziModal, the function with property `onClosed` below finds all such elements on screen with `fa-refresh` class which in this case includes all refresh icons of tabs which are open as well as updater icon and then clicks on all of it using parent.$(".fa-refresh").click();. Eventually, we are not only directing all tabs to refresh upon closing of iziModal but **also updater to open up**, …

Fix iziModal - updater opening

---

modules/calendar/index.php

Initial commit lets Calendar scroll to current local time slot and if current time is like 4 P.M. (with clinic ending time like 5 P.M.), then it scrolls as much as it can and a red line indicator is also added which crosses the current time. Scrolling happens whenever Calendar loads, refreshes or whenever user changes views (1 day, 2 day, week) or navigates through dates (prev, next, today). @teryhill Please have a look.
To do: Add horizontal scroll in Agenda views to accommodate a large number of providers.

Scroll time and provider in Calendar views

---

interface/tags_filters/migrations/Migration_2018_08_22_14_48_11.php

On a large DB, the join on the  tf_patient_tags pivot table caused big performance penalty, so I added a migration to insert an index to pid col of tf_patient_tags pivot table.

Improve performance of patient finder with tags on large DB

---

modules/calendar/search.php

Fix for patient broken link from calendar search page. Procedure click on the search button of calendar. Search a patient between some start date and end date. Results displays quite alright. Now click on the patient name. --> RESULTS: 404 not found tab found.
With new code

fixed broken link

---

interface/usergroup/facilities.php

This PR covers the iziModal part of iziModal-tab refresh - updater opening issue with tab part covered in #1194. Since, updater (#1122) is now in code base with facility iziModal added in #1134, this initial commit fixes opening of updater after closing of facility edit modal. @teryhill Please have a look.

Change facility dynamic iziModal refresh

---

interface/patient_file/summary/stats_full.php

In stats_full.php End date for an issue is displayed as a time when the value is NULL.  Looks goofy with fake negative 1969 date in there...this fixes it, especially when you add additional custom patient ISSUE types.

Medical Issue End-date display

---

sites/default/menu_data.json

When Clicking on Popups > Import , Export and QA Measures > XML Editor, we get unexpected 404.
This PR Fixes #1327

Fixes #1327 - 404 from Import , Export and XML Editor

---

interface/forms/dictation/new.php
interface/forms/reviewofs/new.php
interface/forms/ros/templates/ros/general_new.php
interface/forms/vitals/templates/vitals/general_new.php

Link: Patient->Visits->Current->Clinical->Review of Systems
Work: - There’s a missing api.inc file. Fix this
Add a back button
Link:Patient->Visits->Current->Clinical->Review of Systems Checks
Work: - Add a back button
There’s a missing file error
Link: Patient->Visits->Current->Clinical->Speech dictation
Work: - change “Don’t Save” button to “Cancel” (red)
Padding between textareas
Link: Patient->Visits->Current->Clinical->Vitals
Work: - change “Don’t Save” button to “Cancel” (red)
Fix the missing file error
For **Patient->Visits->Current->Clinical->Review of Systems** and **Patient->Visits->Current->Clinical->Review of Systems>Checks**, the panels are restyled to look cleaner.
FROM:
Also: api.inc link is no longer broken
Finally, not a rant but just a suggestion. The theme data seems to …

Style: Patient->Visits->Current->Clinical

---

interface/usergroup/assets/css/facility.css
interface/usergroup/facility_user.php
interface/usergroup/facility_user_admin.php

**Link**: Admin->User->View Facility->’Click on user’s name’
**Work**: - add some space between “.... Information” and “Back to users” button
-Separate “Save” and “Cancel” buttons
Space between fields`
Bring fields closer to their labels.
**FIXED:**
- add some space between “.... Information” and “Back to users” button
- Separate “Save” and “Cancel” buttons
- Space between fields
- Bring fields closer to their labels.
**From this**
**To this:**

Fix: View facility styling

---

interface/forms/clinical_instructions/new.php

**GCI: Task 4 in EHR UI Grab Bag**
Link: Patient->Visits->Current->Clinical->Clinical instructions
Work: - Centralize the form. -Change tab title from “New encounter” to “Clinical instructions”

UI Fix: Clinical Instructions Form Styling

---

modules/calendar/search.php

The title of the tab is always Calendar now. There is no reason to change it either to "Back to Calendar" or to "Search" or something like that. The tab is still related to Calendar so just keep the name. Added some margins inside the content to fit better.

Fix #1301: Calendar title no longer changes

---

interface/forms/patient_encounter/common.php

Noticed on mouse focus the cursor moves some spaces ahead. Bringing the textarea tag to one line solves this issue

Fixed cursor spacing on mouse focus in text area (New Encounter)

---

interface/themes/style_light.css

Fixes #1291 for light theme.
**Description:**
Changed values in the css so that the tabs other than `current` would also appear as blue. Also made the `current` tab bold.
Note: I had an issue when I was bug hunting where I made changes to the css file but it didn't apply for some reason. I cleared all my Chrome data for the past 24 hours (since I installed EHR last night), and my changes started to register. Not sure what happened there though.
**GIF:**

Fix #1291: Tab Value Colors Changed to Blue from White

---

interface/themes/style_light.css
interface/themes/style_prism.css

Previously the buttons on **New Encounter Form** were hardly visible because of their weird color combinations. I fixed them to white in Light and Prism theme.
Fixes #1341

Fixes #1341 - Turned Button Texts to White

---

interface/patient_file/addr_label.php
interface/patient_file/barcode_label.php
interface/patient_file/label.php

PDFs do not display titles as the pages are not stored with titles in. To add labels to PDF files, a structure similar to the committed changes must be employed. I was tempted to change this for ALL PDF files but was not sure how necessary this would be as they may not all be iframes. I am awaiting for @Trodrige 's view on this. 
Fixes #1336

Fixing Unknown title for PDFs

---

assets/js/DataTables-1.10.16/datatables.css
interface/reports/clinical_stats_by_demographics_report.php
interface/reports/lab_stats_by_demographics_report.php

The table columns adjust their height to the biggest length value in the column. However, the search bars do not follow suit. I added a css styling to make the width of the inputs 100%. The inputs will adjust to the size of the lengthiest data value in the column when data is populated (tested with inspect element in nhanes demo).

Fix #1275: Clinical Reports Enhancement (Dynamically Sized Inputs)

---

library/authentication/password_change.php

Fix : #1451 
Changes made in : library/authentication/password_change.php
Added validation to check blank current password field on clicking save button.

Validation for blank current password

---

interface/patient_file/summary/labdata.php

The issue was that the title was never declared in the respective php file. Just added the tag and it is fixed.

Fix #1298: Lab Overview Title Not Displaying

---

interface/patient_file/summary/add_edit_issue.php

Removed focus from End Date field on the Add issues form so that calendar does not pop up when outcome <Resolved> is selected.

#1246: Calendar opens on medication outcome select <Resolved>

---

modules/calendar/index.php

Continuing #1203, initial commit adds a horizontal scroll bar for provider scroll in agenda views of Calendar. It works by making Calendar slot table overflow its container. One issue was disappearance of scroll bar because of height of `.fc-scroller` and had to add a function to make sure it's visible in all possible states.
@teryhill Please have a look.

Provider scroll in Calendar's agenda views

---

library/appointments.inc.php
modules/calendar/add.php
modules/calendar/css/add.css
modules/calendar/index.php

This first commit adds the interface for this feature where user can enter holidays, vacations in bulk without going to the dates on the calendar to do it. Calendar now has an _add_ button as shown below:
Clicking on this button would open a dialog modal having two tab views/forms:
Add Vacation form
Functionality:
In this tab, user can select a range of consecutive dates of vacation for a selected provider from _Start Date_ to _End Date_. Upon submitting this form, vacation slot would be booked for specified dates and specified provider.
Add Holiday form
Functionality:
In this tab, user can select and _add_ disjoint dates of holiday (which will be shown under _Selected dates_ column) for a particular clinic/facility. Upon submitting this form, holiday slot would be booked for specified …

Managing vacation/holidays in bulk

---

library/globals.inc.php

Fixes Issue #[1484](https://github.com/LibreHealthIO/lh-ehr/issues/1484).
The description for the "Auto-Create New Encounters" property now reads:

Fixes incorrect property setting description

---

interface/patient_tracker/patient_tracker.php

Fixes Issue #[1509](https://github.com/LibreHealthIO/lh-ehr/issues/1509).
The typo was removed, and it now displays the property choice text correctly.

removed flow board property choice typo in local settings

---

interface/patient_tracker/patient_tracker.php

The Flow Board option "Show Exam Room Patient Flow Board" was missing "in" and this was corrected to "Show Exam Room in Patient Flow Board".

Flow Board - "Show Exam Room" Option Grammatical Error

---

interface/patient_tracker/patient_tracker.php

Fixes Issue #1514 
Now, using iziToast, when a user enters a From date greater than a To date or submits the Flow Board form without a date(s), a warning message pops up to let the user know without submitting the form:
Examples:
1) User submits the form with 2019-10-01 to 2019-09-04 date range:
2) User submits form without specifying a date:

form no longer accepts invalid or empty dates

---

interface/patient_tracker/patient_tracker.php

The sixth property setting within the Flow Board Local Settings now says, "Flag Double Booked Appt in Patient Flow Board." This change makes it consistent with the other property setting descriptions.

Fixes Issue #1523 - added missing word in setting description

---

interface/main/tabs/main.php

I decided to go ahead and push this solution until we can further discuss if there needs to be certain modules that have the option and capability to be opened in two tabs.
Right now, none of the default tabs can be opened more than once. If the user tries to open a default module that is already opened, the same tab will reload.
The root cause was that the navigateTab() function that determines if a tab is already opened was not able to correctly identify the default tabs. The default tab URL and names are hard coded in, and after all of the database info initially loads, the URL and name are supposed to both change to reflect the chosen modules in the global settings. However, the URL changed, but not the name.
My solution correctly changes the associated name with each default module …

Fixes Issue #1531 - can no longer open duplicate modules on same screen

---

interface/main/backup.php

Fixes #1329 
<b> tag was directing the title to become "Note" instead of "Backup", so I used the strong tag instead.

Fix #1329: Backup Title Not Displaying Correctly

---

modules/calendar/admin.php

This is the beginning attempt to create a solution for Issue #1525.
I was able to delete the duplicate "Test" category from the Category List through the Calendar Admin Tool. (I actually deleted both, since I originally created the "Test" category and it's not needed anymore.)
What the category list looks like now within the docs server app:
Now, I'm trying to solve the underlying issue: the Calendar Admin Tool allowing category names to be reused. The category names should be unique values. My solution is to have a check when the form is submitted to check if there is a category with that name that already exists. If so, display a message to users using iziModal and keeping the entered form info displayed by not refreshing the form. Otherwise, the new category is created.
I created the …

added check for duplicate category names

---

interface/themes/style_tan.css

@Ngai-E @mhn94  @muarachmann this is a fix for #1576. The text is now visible because I used a brown color. See screenshot below.

Fixed text on button changing to white after clicking button

---

interface/billing/sl_receipts_report.php
interface/reports/collections_report.php
interface/reports/receipts_by_method_report.php
interface/reports/services_by_category.php

Fixes Issues #1556 && #1557 
Added missing labels that were missing next to specific form elements in certain Report forms.
The "Receipts Summary" module now looks like this:

Added missing labels and fixed form alignment

---

modules/calendar/add.php

Now If the 'Start Date' is greater than the 'End Date' a popup shows. This fix is Issue #1630

A Modification In Calendar Date

---

interface/main/main_screen.php
interface/patient_file/letter.php
library/sanitize.inc.php

This is the first test commit towards fixing the csrf vulnerability. Basically, we create a token to validate requests that can manipulate data on the system and verify this each time such request is made. 
This approach makes use of the openssl php extension which can be activated as follows;
1. Open php.ini file located under php installation folder.
2. Search for extension=php_openssl.dll.
3. Uncomment it by removing the semi-colon(;) in front of it.
4. Restart the Apache Server.
So far only the letter.php endpoint has been handled. More commits to come.

begin work on csrf fixes

---

interface/main/backup.php

This is a fix for [Issue 1372](https://github.com/LibreHealthIO/lh-ehr/issues/1372).
Locally, none of the warnings get displayed and backup.php seems to be in the right location according to the URL shown, so my fix targets the security aspect. 
I didn’t see any permission issues from the log reporting options on the server as suggested in the issue report, since the `$cmd` variable in the line of code below from backup.php is responsible for displaying the sensitive info:
`die("\"$cmd\" returned $tmp2: $tmp0");`
I wasn’t sure if displaying the command was imperative. I assumed no since it wasn’t mentioned in the issue report. Thus, my solution removed `$cmd` from the output.

removed sensitive info output in backup.php

---

interface/main/tabs/css/tabs.css

closes #1666 
Updates tabs.css
(Removes the "flex-direction: column;" in the body section of tabs.css to get rid of short tabs in the browser in windows and gives long screen length tabs)

 Fix the short tabs issue in the browser in windows
